In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import special

### Defining input for the attention layer

In [2]:
INPUT_SIZE = 4
X1 = np.array([1, 2, 3, 4])
X2 = np.array([5, 6, 7, 8])
X3 = np.array([2, 0, 1, 0])

BATCH = np.array([X1,
                  X2,
                  X3])

### Define keys and queries matrices

In [3]:
ATTENTION_SIZE = 5

# KEY_M = np.ones((4, ATTENTION_SIZE), dtype="int")
# KEY_M = np.array([np.arange(1, ATTENTION_SIZE+1) for _ in range(len(X1))])
# QUERY_M = np.array([np.arange(1, 5) for _ in range(ATTENTION_SIZE)]).T
# VALUE_M = QUERY_M + 0.3

KEY_M = np.random.random((INPUT_SIZE, ATTENTION_SIZE))
QUERY_M = np.random.random((INPUT_SIZE, ATTENTION_SIZE))
VALUE_M = np.random.random((INPUT_SIZE, ATTENTION_SIZE))


print(f"key matrix:\n {KEY_M}\n")
print(f"query matrix:\n {QUERY_M}\n")
print(f"value matrix:\n {VALUE_M}\n")

key matrix:
 [[0.13814231 0.8731915  0.51151005 0.72582011 0.95036389]
 [0.60210799 0.23468904 0.14263186 0.80795999 0.42593447]
 [0.95652938 0.271889   0.90636572 0.01681083 0.02756798]
 [0.27835921 0.4553256  0.78750757 0.76632905 0.35947534]]

query matrix:
 [[0.94006615 0.84446622 0.02131257 0.20925241 0.85826604]
 [0.64090179 0.33988937 0.56320776 0.92168833 0.77486216]
 [0.41077166 0.16167661 0.46416962 0.33224631 0.44153737]
 [0.3406976  0.69500717 0.72462868 0.26272935 0.18809307]]

value matrix:
 [[0.29339513 0.31530918 0.96702686 0.65722146 0.91285902]
 [0.82527956 0.54796411 0.58954936 0.77882286 0.11837037]
 [0.7735471  0.89792396 0.19851922 0.83874741 0.43272577]
 [0.0070122  0.19577224 0.97789047 0.19845109 0.50700146]]



In [4]:
KEY_REP = []
QUERY_REP = []
VALUE_REP = []

for X in BATCH:
    KEY_REP.append(X @ KEY_M)
    QUERY_REP.append(X @ QUERY_M)
    VALUE_REP.append(X @ VALUE_M)

KEY_REP = np.array(KEY_REP)
QUERY_REP = np.array(QUERY_REP)
VALUE_REP = np.array(VALUE_REP)

print(f"key repr:\n {KEY_REP}\n")
print(f"query repr:\n {QUERY_REP}\n")
print(f"value repr:\n {VALUE_REP}\n")

key repr:
 [[ 5.32538329  3.97953898  6.66590118  5.45748878  3.32283814]
 [13.22593888 11.31991956 16.05796196 14.7251687  10.37620488]
 [ 1.23281401  2.01827201  1.92938583  1.46845104  1.92829576]]

query repr:
 [[ 4.81697513  4.78930346  5.43875166  4.10028543  4.48497475]
 [14.14672395 12.95346092 12.5320262  11.00395106 13.53600931]
 [ 2.29090397  1.85060904  0.50679477  0.75075113  2.15806945]]

value repr:
 [[ 4.29264435  4.88809824  6.65324514  5.52491378  4.47578291]
 [11.88958032 12.7159762  17.5851888  15.41788507 12.35960937]
 [ 1.36033736  1.52854232  2.13257294  2.15319033  2.25844381]]



In [5]:
KEY_QUERY = KEY_REP @ QUERY_REP.T
print(f"initial key @ query result:\n {KEY_QUERY}\n")

#GEWOON HANDIG OM TE DOEN VOOR SMOOTH LOSS SURFACE - BOYOS VAN GOOGLE
KEY_QUERY_SCALED = (KEY_QUERY / np.sqrt(ATTENTION_SIZE)) / 1000
print(f"scaled key @ query result:\n {KEY_QUERY_SCALED}\n")

KEY_QUERY_FINAL = special.softmax(KEY_QUERY_SCALED, axis=1)
print(f"final key @ query result:\n {KEY_QUERY_FINAL}\n")


initial key @ query result:
 [[118.24574668 315.45468563  34.21088772]
 [312.17322738 837.46208333  92.83370028]
 [ 40.76742812 110.02319356  12.80093104]]

scaled key @ query result:
 [[0.05288111 0.14107562 0.01529957]
 [0.13960811 0.37452443 0.04151649]
 [0.01823175 0.04920387 0.00572475]]

final key @ query result:
 [[0.32729834 0.35747543 0.31522623]
 [0.31532126 0.39881925 0.28585948]
 [0.33123248 0.34165197 0.32711555]]



In [6]:
QKV = KEY_QUERY_FINAL @ VALUE_REP

print(f"final result:\n {QKV}\n")

final result:
 [[6.08402221 6.62735211 9.13611192 7.99855225 6.5950937 ]
 [6.48422092 7.04964576 9.72083772 8.50658208 6.98615728]
 [5.92894929 6.4635452  8.90938307 7.80192376 6.44398167]]

